In [1]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split

In [2]:
dataset= sklearn.datasets.load_breast_cancer()

In [3]:
print(dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [4]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [5]:
df.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [6]:
df.shape

(569, 30)

In [8]:
x = df
y = dataset.target

In [9]:
x

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

Standardize data

In [11]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
df1=ss.fit_transform(x)
df1

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

MinMaxScalr data

In [30]:
#from sklearn.preprocessing import MinMaxScaler
#min = MinMaxScaler()
#df3 = min.fit_transform(x)
#df3

MaxAbsAcaler data

In [29]:
#from sklearn.preprocessing import MaxAbsScaler
#max = MaxAbsScaler()
#df2 = max.fit_transform(x)
#df2

Robust data

In [28]:
#from sklearn.preprocessing import RobustScaler
#rob = RobustScaler()
#df4 = rob.fit_transform(x)
#df4

Splitting data for trainig and testing

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=3)

In [45]:
print(x.shape , x_train.shape,x_test.shape)

(569, 30) (455, 30) (114, 30)


In [46]:
from sklearn.linear_model import LinearRegression
rig = LinearRegression()
df5 = rig.fit(x_train , y_train)

In [47]:
y_pred = rig.predict(x_test)
y_pred

array([ 1.00559733e+00,  6.61345837e-01,  8.95805470e-01,  9.97432659e-01,
        3.04172691e-01,  9.17350871e-01,  8.85870811e-01,  1.16554538e+00,
        1.18284116e+00,  9.40837135e-01,  1.17959512e+00,  3.96857665e-01,
        1.05625197e+00,  8.67585848e-01,  9.73193301e-01,  8.84681258e-01,
        8.88650855e-01,  1.13831216e+00, -6.32123617e-02,  6.97439920e-01,
        9.06867886e-01,  9.57357231e-01,  7.05215535e-01,  7.31719651e-01,
        1.05693523e+00,  1.05679830e+00,  1.02415484e+00, -1.39903439e-02,
       -1.70450926e-01,  7.88593835e-01,  4.45119106e-01,  1.44009289e+00,
        7.86343757e-01,  1.04261598e+00,  8.58314479e-01,  1.02644846e+00,
        1.05658924e+00,  1.20820187e+00,  9.16922502e-02, -8.35849502e-03,
       -6.71729191e-02,  9.70460653e-01,  9.40048066e-01,  3.57595501e-01,
        7.51682235e-01,  3.70950341e-01,  5.12973806e-01,  6.59486233e-01,
        3.49252341e-01,  9.75077089e-01,  3.61100424e-02,  8.76651289e-01,
        7.81811889e-01,  

In [35]:
rig.score(y_)

ValueError: ignored