numpy

In [4]:
# importing numpy library

import numpy as np
from time import process_time

list vs numpy time taken

In [5]:
#list

list =[i for i in range(10000)]
start_time=process_time() 
list =[i+5 for i in list]
end_time=process_time()
print(end_time - start_time)

0.0009334429999996452


In [6]:
#array

array = np.array([i for i in range(10000)])
start_time=process_time() 
array = ([i for i in array])
end_time=process_time()
print(end_time - start_time)

0.000665397000000123


Numpy array


In [7]:
list1=[(1,2,3,4,5),(6,7,8,9,0)]
print(list1)
type(list1)

[(1, 2, 3, 4, 5), (6, 7, 8, 9, 0)]


list

In [8]:
# dim array
array=np.array([(1,2,3,4,5),(6,7,8,9,0),(1,2,3,4,5)])
print(array)
type(array)
array.shape

[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]]


(3, 5)

In [9]:

array1=np.array([(1,2,3,4,5),(6,7,8,9,0)],dtype=float)
print(array1)
type(array1)
array1.shape

[[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]]


(2, 5)

In [10]:
# numpy array with zero

a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# numpy array with one
b=np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# array with particular value
c=np.full((5,5),2)
print(c)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [13]:
#identity matrix
a=np.eye((5))
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# array with random value

b=np.random.random((4,5))
print(b)

[[0.71934642 0.94516145 0.87767979 0.57484696 0.52489397]
 [0.89015483 0.78711691 0.27252812 0.62469606 0.03057807]
 [0.12876829 0.74112044 0.15034817 0.62561358 0.35366378]
 [0.32959207 0.51140967 0.97914379 0.16296113 0.3728914 ]]


In [15]:
# array with random value in range
b=np.random.randint(1,20,(4,5))
print(b)

[[ 9 17  5 11 16]
 [15 10  1  9  9]
 [18  7 11 17 14]
 [10  9 16 16 19]]


In [16]:
# array of even spaced value
c=np.linspace(1,10,5)
print(c)

[ 1.    3.25  5.5   7.75 10.  ]


In [17]:
# array of even spaced value specifying step
c=np.arange(1,10,2)
print(c)

[1 3 5 7 9]


In [18]:
# convert list to array
list2=[1,2,3,4,5]
a=np.asarray(list2)
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [19]:
# array dimention check
b=np.random.randint(1,20,(4,5))
print(b)

print(b.shape)
print(b.ndim)
print(b.size)

[[ 4 18 18 11  2]
 [17  4 10  6  2]
 [18 17  1 14 18]
 [ 9 13 16 15  4]]
(4, 5)
2
20


In [20]:
# checking data type of this
print(b.dtype)

int64


In [21]:
#mathmetical operation on array
a=np.random.randint(1,10,(5,5))
b=np.random.randint(10,30,(5,5))

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.add(a,b))

[[33 28 17 20 36]
 [20 14 18 20 14]
 [37 25 22 31 32]
 [27 37 21 34 27]
 [22 38 29 23 24]]
[[-15 -10 -13 -10 -22]
 [-18  -8  -4 -16 -12]
 [-19  -9 -12 -21 -18]
 [-15 -19 -11 -16 -21]
 [ -8 -20 -17  -9 -18]]
[[216 171  30  75 203]
 [ 19  33  77  36  13]
 [252 136  85 130 175]
 [126 252  80 225  72]
 [105 261 138 112  63]]
[[0.375      0.47368421 0.13333333 0.33333333 0.24137931]
 [0.05263158 0.27272727 0.63636364 0.11111111 0.07692308]
 [0.32142857 0.47058824 0.29411765 0.19230769 0.28      ]
 [0.28571429 0.32142857 0.3125     0.36       0.125     ]
 [0.46666667 0.31034483 0.26086957 0.4375     0.14285714]]
[[33 28 17 20 36]
 [20 14 18 20 14]
 [37 25 22 31 32]
 [27 37 21 34 27]
 [22 38 29 23 24]]


In [27]:
# transpose
a=np.random.randint(1,10,(2,3))
print(a)
a.shape
trans=np.transpose(a)
print(trans)
trans.shape


[[8 9 2]
 [7 3 9]]
[[8 7]
 [9 3]
 [2 9]]


(3, 2)

In [25]:
# reshape
a=np.random.randint(10,20,(3,6))
print(a)
a.shape

b=a.reshape(6,3)
print(b)
b.shape


[[15 12 11 11 15 19]
 [19 12 19 10 15 10]
 [19 15 11 10 13 15]]
[[15 12 11]
 [11 15 19]
 [19 12 19]
 [10 15 10]
 [19 15 11]
 [10 13 15]]


(6, 3)